import { chromium } from "playwright";
import { mkdirSync } from "node:fs";
const OUT = process.env.OUT || "/tmp/full"; mkdirSync(OUT, { recursive: true });
const b = await chromium.launch();
const c = await b.newContext({ viewport:{width:1440,height:900}, reducedMotion:"reduce" });
const p = await c.newPage();
await p.goto("http://localhost:5341/", { waitUntil:"networkidle", timeout:60000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${OUT}/home-full.png`, fullPage:true });
console.log("saved", await p.evaluate(()=>document.documentElement.scrollHeight)+"px");
await b.close();
